version: '3.1'

services:

  db:
    image: mysql:latest
    container_name: erlang-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: erlang
      MYSQL_ROOT_PASSWORD: erlang
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    networks:
      - erlang
  rest:
    image: erlang:latest
    container_name: erlang-rest
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./erlang:/erlang
    ports:
      - 8080:8080
    network_mode: host
#    networks:    
#      - erlang
networks:
  erlang:
    internal: true