PROJECT = erlang
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

DEPS = cowboy mysql
dep_cowboy_commit = 2.8.0
dep_mysql = git https://github.com/mysql-otp/mysql-otp 1.7.0

DEP_PLUGINS = cowboy mysql


include erlang.mk
